services:
  sherlock:
    build: .
    container_name: sherlock-dev
    ports:
      - "8000:7860"
    env_file:
      - .env
    #  mount it as a volume to see changes to your app.py without rebuilding
    volumes:
      - ./app.py:/home/user/app/app.py
    restart: unless-stopped